# Generated by Django 5.2.1 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_remove_learningtrack_progression_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningtrack",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="learningtrack",
            name="summary",
        ),
        migrations.AddField(
            model_name="userlearningtrack",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userlearningtrack",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
