# Generated by Django 5.2.1 on 2025-05-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_learningtrack_last_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="num_of_task",
        ),
    ]
