# Generated by Django 5.2.1 on 2025-05-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_remove_task_num_of_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="learning_track",
        ),
        migrations.RemoveField(
            model_name="task",
            name="learning_track",
        ),
        migrations.AddField(
            model_name="note",
            name="user_learning_track",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tracker.userlearningtrack",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user_learning_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tracker.userlearningtrack",
            ),
        ),
    ]
