# Generated by Django 5.2.1 on 2025-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_remove_note_learning_track_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="note",
        ),
        migrations.AlterField(
            model_name="userlearningtrack",
            name="progression",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
