# Generated by Django 5.2.1 on 2025-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0007_remove_task_note_alter_userlearningtrack_progression_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="learningtrack",
            name="language",
            field=models.CharField(default="python", max_length=20),
        ),
    ]
