# Generated by Django 5.2.1 on 2025-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_learningtrack_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningtrack",
            name="language",
        ),
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(default="python", max_length=20),
        ),
    ]
