# Generated by Django 5.2.1 on 2025-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_learningtrack_created_by_learningtrack_is_custom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningtrack",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="category",
            name="language",
        ),
        migrations.AddField(
            model_name="learningtrack",
            name="language",
            field=models.CharField(default="python", max_length=20),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
