# Generated by Django 5.2.1 on 2025-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0011_remove_learningtrack_topics_remove_category_language_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="learningtrack",
            name="language",
        ),
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(default="python", max_length=20),
        ),
        migrations.AddField(
            model_name="learningtrack",
            name="topics",
            field=models.ManyToManyField(related_name="tracks", to="tracker.topic"),
        ),
    ]
