# Generated by Django 5.2.6 on 2025-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_topic_remove_learningtrack_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
