# Generated by Django 5.2.6 on 2025-09-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_task_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="difficulty",
        ),
    ]
