# Generated by Django 5.2.1 on 2026-05-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_remove_task_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
