# Generated by Django 5.2.1 on 2026-05-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_remove_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningtrack",
            name="topics",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
