# Generated by Django 5.2.1 on 2026-05-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_remove_learningtrack_topics_delete_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user_learning_track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tracker.userlearningtrack",
            ),
        ),
    ]
