# Generated by Django 5.2.1 on 2026-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_alter_task_user_learning_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="language",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="task",
            name="starter_code",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
