# Generated by Django 5.2.1 on 2026-05-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_task_description_task_language_task_starter_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlearningtrack",
            name="progression",
        ),
    ]
